# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: windows-2019

steps:
  - task: AzurePowerShell@5
    inputs:
      ScriptType: 'InlineScript'
      azureSubscription: 'lnxSC'
      azurePowerShellVersion: LatestVersion
      Inline: |
        $ErrorActionPreference='Continue'
        Connect-AzContainerRegistry -name lnxcr
        Connect-AzContainerRegistry -name lnxcr -username $(sp) -password $(pwd)
        