
parameters:
- name: OOBBranch
  displayName: Branch for OOB pipeline
  type: string
  default: 'none'
jobs:
- job: BumpUpVersion
  timeoutInMinutes: 180
  pool: pool-windows-2019
  variables:
    BumpUpBranch: test
  steps:

  - task: PowerShell@2
    name: test
    inputs:
      targetType: 'inline'
      script: |
        write-host ${{ parameters.OOBBranch }}
        write-host '${{ parameters.OOBBranch }}'
        write-host ('${{ parameters.OOBBranch }}' -eq 'hey')
    condition: and(succeeded(), eq('${{ parameters.OOBBranch }}', 'hey'))
  - task: PowerShell@2
    name: test1
    inputs:
      targetType: 'inline'
      script: |
          Write-Host "not equal hey"
          Write-Host ${{ parameters.OOBBranch }}
          write-host ('${{ parameters.OOBBranch }}' -eq 'hey')
          $b = '${{ parameters.OOBBranch }}'
          write-host ($b -eq 'hey')
    condition: and(succeeded(), ne('${{ parameters.OOBBranch }}', 'hey'))
  - task: PowerShell@2
    name: test2
    inputs:
      targetType: 'inline'
      script: |
          Write-Host "equal hey"
          Write-Host ${{ parameters.OOBBranch }}
    condition: and(succeeded(), eq('${{ parameters.OOBBranch }}', 'hey'))
