parameters:
- name: ServiceName
  displayName: Service to OOB release
  type: string
  default: Databricks
- name: BumpUpVersion
  displayName: Need BumpUpVersion
  type: boolean
  default: true
stages:
- stage: OOBRelease
  displayName: OOBRelease
  variables:
    name: BumpUpBranch
  jobs:
  - job: BumpUpVersion
    timeoutInMinutes: 180
    pool: pool-windows-2019
    steps:
    - task: PowerShell@2
      name: bump
      displayName: get bump up branch
      inputs:
        targetType: 'inline'
        script: |
          $a = $${{ parameters.BumpUpVersion }}
          Write-Host $a
          Write-Host ($${{ parameters.BumpUpVersion }} -eq $True )
          if ($${{ parameters.BumpUpVersion }} -eq $true ) {
              $str = "codeoob/${{ parameters.ServiceName }}"
              Write-Host $str
          } else {
              $str = "hello"
              Write-Host $str
          }
          Write-Host "##vso[task.setvariable variable=BumpUpBranch;isOutput=true]hello"
          Write-Host $str
- stage: output
  variables:
    BumpUpBranch: $[stageDependencies.OOBRelease.BumpUpVersion.outputs['bump.BumpUpBranch']]
  jobs:
  - job: output 
    steps:
    - task: PowerShell@2
      displayName: output
      condition: and(succeeded(), ne('$(BumpUpBranch)', '''hello'''))
      inputs:
        targetType: 'inline'
        script: |
          Write-Host $(BumpUpBranch)