parameters:
- name: ServiceName
  displayName: Service to OOB release
  type: string
  default: Databricks
- name: BumpUpVersion
  displayName: Need BumpUpVersion
  type: boolean
  default: true
stages:
- stage: OOBRelease
  displayName: OOBRelease
  variables:
    BumpUpBranch: none 
  jobs:
  - job: BumpUpVersion
    timeoutInMinutes: 180
    pool: pool-windows-2019
    steps:
    - task: PowerShell@2
      name: bump
      displayName: get bump up branch
      inputs:
        targetType: 'inline'
        script: |
          if (${{ parameters.BumpUpVersion }} -eq $true) {
              Write-Host "##vso[task.setvariable variable=BumpUpBranch;isOutput=true]codeoob/${{ parameters.ServiceName }}"
          } else {
              Write-Host "##vso[task.setvariable variable=BumpUpBranch;isOutput=true]hello"
          }
  - job: output
    dependsOn: BumpUpVersion
    variables:
      BumpUpBranch: $[stageDependencies.BumpUpVersion.outputs['bump.BumpUpBranch']]
    steps:
    - task: PowerShell@2
      displayName: get bump up branch
      inputs:
        targetType: 'inline'
        script: |
          Write-Host $(BumpUpBranch)