variables:
  - name: happy
    value: aaa
jobs:
  - job: OOBRelease
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          echo "##vso[task.setvariable variable=happy]bbb"
          write-host $(happy)