variables:
    name: a
    value: aaa
jobs:
  - job: OOBRelease
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          echo "##vso[task.setvariable variable=a]bbb"
          echo $(a)