variables:
- name: BumpUpBranch
  value: none 
jobs:
  - job: OOBRelease
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          if ($false -eq $true) {
              Write-Host "##vso[task.setvariable variable=BumpUpBranch]codeoob"
          } else {
              Write-Host "##vso[task.setvariable variable=BumpUpBranch]none"
          }
          write-host $(BumpUpBranch)