trigger: none
jobs:
  - job: test
    pool:
      vmImage: ubuntu-20.04
    steps:
    - task: AzurePowerShell@5
      displayName: 'Push packages to storage account'
      inputs:
        azureSubscription: 'lnxtest'
        ScriptType: InlineScript
        Inline: |
          $context = New-AzStorageContext -StorageAccountName "acrteststorageaccount"
          Set-AzStorageBlobContent -Container test -Context $context -File "./leetcode.iml" -Force
        azurePowerShellVersion: LatestVersion
          
