variables:
- name: one
  value: initialValue 
- name: bumpbranch
  value: none 
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      if ($false -eq $true) {
          Write-Host "##vso[task.setvariable variable=bumpbranch]codeoob"
      } else {
          Write-Host "##vso[task.setvariable variable=bumpbranch]hello"
      }
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
       Write-Host ${{ variables.bumpbranch }}
       echo $(bumpbranch) 