parameters:
- name: ServiceName
  displayName: Service to OOB release
  type: string
  default: Databricks
- name: BumpUpVersion
  displayName: Need BumpUpVersion
  type: boolean
  default: true
stages:
- stage: OOBRelease
  displayName: OOBRelease
  variables:
    name: BumpUpBranch
  jobs:
  - job: BumpUpVersion
    timeoutInMinutes: 180
    pool: pool-windows-2019
    steps:
    - task: PowerShell@2
      name: bump
      displayName: get bump up branch
      inputs:
        targetType: 'inline'
        script: |
          if (${{ parameters.BumpUpVersion }}) {
              $str = "codeoob/${{ parameters.ServiceName }}"
          } else {
              $str = "hello"
          }
          Write-Host "##vso[task.setvariable variable=BumpUpBranch;isOutput=true]$str"
- stage: output
  variables:
    BumpUpBranch: $[stageDependencies.OOBRelease.BumpUpVersion.outputs['bump.BumpUpBranch']]
  jobs:
  - job: output 
    steps:
    - task: PowerShell@2
      displayName: output
      inputs:
        targetType: 'inline'
        script: |
          Write-Host $(BumpUpBranch)