parameters:
- name: ServiceName
  displayName: Service to OOB release
  type: string
  default: Databricks
- name: BumpUpVersion
  displayName: Need BumpUpVersion
  type: boolean
  default: true
variables:
- name: BumpUpBranch
  value: none 
stages:
- stage: OOBRelease
  displayName: OOBRelease
  jobs:
  - job: BumpUpVersion
    timeoutInMinutes: 180
    pool: pool-windows-2019
    steps:
    - task: PowerShell@2
      displayName: get bump up branch
      inputs:
        targetType: 'inline'
        script: |
          if (${{ parameters.BumpUpVersion }} -eq $true) {
              Write-Host "##vso[task.setvariable variable=BumpUpBranch]codeoob/${{ parameters.ServiceName }}"
          } else {
              Write-Host "##vso[task.setvariable variable=BumpUpBranch]none"
          }
- stage: Codesign
  dependsOn: OOBRelease
  jobs:
  - job: BumpUpVersion
    timeoutInMinutes: 180
    pool: pool-windows-2019
    steps:
    - task: PowerShell@2
      displayName: 1111
      inputs:
        targetType: 'inline'
        script: |
            Write-Host $(BumpUpBranch)