# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: MCR Images Verification

parameters:
  - name: azVersion
    displayName: Az version
    type: string
    default: 8.0.0
  - name: imageList
    type: object
    default:
      - ubuntu-18.04
      - ubuntu-20.04
      - ubuntu-22.04     
      - mariner-1
      - mariner-2
      - debian-10
      - debian-11
      - centos-7
      - alpine-3.13
      - alpine-3.14

pool:
  vmImage: ubuntu-20.04
  
stages:  
- stage: Validation
  jobs:
    - job: generator
      steps:
      - powershell: |
          $list='${{Converttojson(parameters.imageList)}}'|ConvertFrom-Json
          foreach ($name in $list){
            $MatrixStr="$MatrixStr,'" + $name.Replace("-","_") + "':{'image':'$name'}"
          }
          $MatrixStr=$MatrixStr.Substring(1)
          Write-Host "##vso[task.setVariable variable=legs;isOutput=true]{$MatrixStr}"
        name: mtrx
    - job: 
      timeoutInMinutes: 90
      displayName: "TestJob"
      dependsOn: generator
      strategy:
        matrix: $[ dependencies.generator.outputs['mtrx.legs'] ]
        maxParallel: 5
      steps:
      - checkout: none
      - task: AzurePowerShell@5
        displayName: Verify images - $(image)
        inputs:
          ScriptType: InlineScript
          azurePowerShellVersion: LatestVersion
          azureSubscription: $(AzureSubscription)
          Inline: |
            docker pull mcr.microsoft.com/azure-powershell:${{parameters.azVersion}}-$(image)
            $actualVersion=$(docker run -i mcr.microsoft.com/azure-powershell:${{parameters.azVersion}}-$(image) pwsh -Command "(Get-Module Az -ListAvailable).Version.ToString()")
            if ($actualVersion -eq "${{parameters.azVersion}}")
            {
              Write-Host "MCR image contains expected Az version."
            }
            else
            {
              Write-Error "Az module or its version is not found"
            }
          failOnStandardError: true