variables:
  BumpUpBranch: hello
stages:
  - stage: OOBRelease
    displayName: OOBRelease
    jobs:
    - job: test
      timeoutInMinutes: 180
      steps:
      - task: PowerShell@2
        name: test
        inputs:
          targetType: 'inline'
          script: |
            write-host $(BumpUpBranch)
            write-host '$(BumpUpBranch)'
            write-host '$(BumpUpBranch)' -eq 'none'
            write-host $(BumpUpBranch) -eq 'none'
    - job: BumpUpVersion
      timeoutInMinutes: 180
      pool: pool-windows-2019
      variables:
        NeedBumpUp: true
      steps:
      - task: PowerShell@2
        displayName: get changelog info
        name: outputinfo
        inputs:
          targetType: 'inline'
          script: |
            echo "##vso[task.setvariable variable=BumpUpBranch;isOutput=true]none"
  
  - stage: test
    variables:
      BumpUpBranch: $[stageDependencies.OOBRelease.BumpUpVersion.outputs['outputinfo.BumpUpBranch']]
    jobs:
    - template: azure-pipelines.yml
      parameters:
        OOBBranch: $[variables.var]